### ISSUE TITLE
how to solve ImportError: cannot import name 'six'

### ISSUE THREAD

**Issue by huaji1992** [NicolasHug/Surprise#207]
C:\WINDOWS\system32>pip install scikit-surprise
Collecting scikit-surprise
  Using cached https://files.pythonhosted.org/packages/4d/fc/cd4210b247d1dca421c25994740cbbf03c5e980e31881f10eaddf45fdab0/scikit-surprise-1.0.6.tar.gz
Could not import setuptools which is required to install from a source distribution.
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\req\req_install.py", line 387, in setup_py
    import setuptools  # noqa
  File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\__init__.py", line 10, in <module>
    from setuptools.extern.six.moves import filter, map
  File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\extern\__init__.py", line 1, in <module>
    from pkg_resources.extern import VendorImporter
  File "C:\ProgramData\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 50, in <module>
    from pkg_resources.extern import six
ImportError: cannot import name 'six'

**Comment by NicolasHug** [comment]
pip install -U setuptools 
?

**Comment by NicolasHug** [comment]
Anyway this is not related to surprise so I'm closing the issue
