### ISSUE TITLE
ImportError: cannot import name 'similarities'

### ISSUE THREAD

**Issue by xiayank** [NicolasHug/Surprise#209]
#### Description

I tried to run the basic_usage.py, however, it gave me `ImportError: cannot import name 'similarities'`. I think I installed it successfully and have numpy, cython and gcc.

Here is some log:
1. pip3 install scikit-surprise
```
pip3 install scikit-surprise
Requirement already satisfied: scikit-surprise in /Users/NIC/Downloads/Courses/Recommendation System/MyCode/surprise (1.0.6)
Requirement already satisfied: joblib>=0.11 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from scikit-surprise) (0.12.5)
Requirement already satisfied: numpy>=1.11.2 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from scikit-surprise) (1.15.2)
Requirement already satisfied: scipy>=1.0.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from scikit-surprise) (1.1.0)
Requirement already satisfied: six>=1.10.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from scikit-surprise) (1.10.0)
```
2. python3 setup.py install
```
logs ....

Using /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Searching for numpy==1.15.2
Best match: numpy 1.15.2
Adding numpy 1.15.2 to easy-install.pth file

Using /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Searching for joblib==0.12.5
Best match: joblib 0.12.5
Adding joblib 0.12.5 to easy-install.pth file

Using /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Finished processing dependencies for scikit-surprise==1.0.6
```
#### Steps/Code to Reproduce

```
python3 examples/basic_usage.py
```
#### Versions
```
>>> import platform; print(platform.platform())
Darwin-16.7.0-x86_64-i386-64bit
>>> import sys; print("Python", sys.version)
Python 3.6.1 (v3.6.1:69c0db5050, Mar 21 2017, 01:21:04)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
>>> import surprise; print("surprise", surprise.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/NIC/Downloads/Courses/Recommendation System/MyCode/surprise/surprise/__init__.py", line 3, in <module>
    from .prediction_algorithms import AlgoBase
  File "/Users/NIC/Downloads/Courses/Recommendation System/MyCode/surprise/surprise/prediction_algorithms/__init__.py", line 23, in <module>
    from .algo_base import AlgoBase
  File "/Users/NIC/Downloads/Courses/Recommendation System/MyCode/surprise/surprise/prediction_algorithms/algo_base.py", line 13, in <module>
    from .. import similarities as sims
ImportError: cannot import name 'similarities'
```

Looking forward you reply. Thanks!

**Comment by NicolasHug** [comment]
You don't need to run ``python3 setup.py install`` if you already used `pip`.

I don't really know why but sometimes when I install surprise I have to log out of the console and come back for it to work.

**Comment by xiayank** [comment]
@NicolasHug YES! I quit my console then come back and run it again. It works! Thank you!

**Comment by yustiks** [comment]
I have the same issue when I debug the code. What could be the problem?
