### ISSUE TITLE
syntax error upon install

### ISSUE THREAD

**Issue by owocki** [NicolasHug/Surprise#316]
#### Description

i get this error when installing surprise

```
  ERROR: Complete output from command /usr/local/bin/python /usr/local/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-o3dgdx4y/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- wheel setuptools 'Cython>=0.29.2' 'numpy==1.13.3; python_version=='"'"'3.5'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.13.3; python_version=='"'"'3.6'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.14.5; python_version>='"'"'3.7'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.5'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.6'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.16.0; python_version>='"'"'3.7'"'"' and platform_system=='"'"'AIX'"'"'':
  ERROR: Traceback (most recent call last):
    File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/usr/local/lib/python3.7/site-packages/pip/__main__.py", line 16, in <module>
      from pip._internal import main as _main  # isort:skip # noqa
    File "/usr/local/lib/python3.7/site-packages/pip/_internal/__init__.py", line 40, in <module>
      from pip._internal.cli.autocompletion import autocomplete
    File "/usr/local/lib/python3.7/site-packages/pip/_internal/cli/autocompletion.py", line 8, in <module>
      from pip._internal.cli.main_parser import create_main_parser
    File "/usr/local/lib/python3.7/site-packages/pip/_internal/cli/main_parser.py", line 12, in <module>
      from pip._internal.commands import (
    File "/usr/local/lib/python3.7/site-packages/pip/_internal/commands/__init__.py", line 6, in <module>
      from pip._internal.commands.completion import CompletionCommand
    File "/usr/local/lib/python3.7/site-packages/pip/_internal/commands/completion.py", line 6, in <module>
      from pip._internal.cli.base_command import Command
    File "/usr/local/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 25, in <module>
      from pip._internal.index import PackageFinder
    File "/usr/local/lib/python3.7/site-packages/pip/_internal/index.py", line 41, in <module>
      from pip._internal.wheel import Wheel
    File "/usr/local/lib/python3.7/site-packages/pip/_internal/wheel.py", line 7, in <module>
      import compileall
    File "/usr/local/lib/python3.7/compileall.py", line 20, in <module>
      from concurrent.futures import ProcessPoolExecutor
    File "/usr/local/lib/python3.7/site-packages/concurrent/futures/__init__.py", line 8, in <module>
      from concurrent.futures._base import (FIRST_COMPLETED,
    File "/usr/local/lib/python3.7/site-packages/concurrent/futures/_base.py", line 381
      raise exception_type, self._exception, self._traceback
                          ^
  SyntaxError: invalid syntax
  ----------------------------------------
ERROR: Command "/usr/local/bin/python /usr/local/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-o3dgdx4y/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- wheel setuptools 'Cython>=0.29.2' 'numpy==1.13.3; python_version=='"'"'3.5'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.13.3; python_version=='"'"'3.6'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.14.5; python_version>='"'"'3.7'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.5'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.6'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.16.0; python_version>='"'"'3.7'"'"' and platform_system=='"'"'AIX'"'"''" failed with error code 1 in None
```

#### Steps/Code to Reproduce

run `pip install scikit-surprise`

#### Expected Results
module is installed 
#### Actual Results
stack trace with exception 

#### Versions

```
bash-4.4# python3
Python 3.7.1 (default, Dec 21 2018, 03:21:42)
[GCC 6.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform; print(platform.platform())

Linux-4.9.184-linuxkit-x86_64-with
>>> import sys; print("Python", sys.version)
Python 3.7.1 (default, Dec 21 2018, 03:21:42)
[GCC 6.4.0]
>>> import surprise; print("surprise", surprise.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'surprise'
>>>
```

**Comment by NicolasHug** [comment]
is there something wrong with your env?

The syntax error comes from `    File "/usr/local/lib/python3.7/site-packages/concurrent/futures/_base.py", line 381`

**Comment by owocki** [comment]
i ran `rm -Rf /usr/local/lib/python3.7/site-packages/concurrent` (per https://www.pythonanywhere.com/forums/topic/12390/ ) and that fixed this issue!
