### ISSUE TITLE
ValueError: could not convert string to float: rating, when loading CSV data

### ISSUE THREAD

**Issue by MonaiThang** [NicolasHug/Surprise#41]
I followed the [load_custom_dataset.py](https://github.com/NicolasHug/Surprise/blob/master/examples/load_custom_dataset.py) example and try to write my own version like this:
```
reader = Reader(line_format='user item rating timestamp', sep=',', rating_scale=(1, 5), skip_lines=0)
data = Dataset.load_from_file('ml-latest-small/ratings.csv', reader=reader)
```
When I run those 2 lines, it gives me the error as below:
```
Traceback (most recent call last):
  File "run2.py", line 9, in <module>
    data = Dataset.load_from_file('ml-latest-small/ratings.csv', reader=reader)
  File "/usr/local/lib/python2.7/site-packages/surprise/dataset.py", line 173, in load_from_file
    return DatasetAutoFolds(ratings_file=file_path, reader=reader)
  File "/usr/local/lib/python2.7/site-packages/surprise/dataset.py", line 306, in __init__
    self.raw_ratings = self.read_ratings(self.ratings_file)
  File "/usr/local/lib/python2.7/site-packages/surprise/dataset.py", line 205, in read_ratings
    itertools.islice(f, self.reader.skip_lines, None)]
  File "/usr/local/lib/python2.7/site-packages/surprise/dataset.py", line 455, in parse_line
    return uid, iid, float(r) + self.offset, timestamp
ValueError: could not convert string to float: rating
```

Is it possible to load the custom data from a CSV file successfully?
Thank you.

**Comment by NicolasHug** [comment]
Hi,
What are the first few lines of your file? The error seems to indicate that there's a header line that you are not ignoring (using the skip parameter)

Nicolas

**Comment by MonaiThang** [comment]
Hi Nicolas,

Thank you for your reply.
The first 3 lines of the csv file are:
```
userId,movieId,rating,timestamp
1,31,2.5,1260759144
1,1029,3.0,1260759179
```
Now I just set the skip_lines to 1 and it works.
