### ISSUE TITLE
Problem between decimal and float value

### ISSUE THREAD

**Issue by prsolucoes** [NicolasHug/Surprise#55]
Hi,

I made the rating for my dataset, and im selecting all from the table of database to make the prediction.

My ratings are between 0.0 and 10.0, but after some time processing i have error:

```
Traceback (most recent call last):
  File "process.py", line 112, in <module>
    predictions = algo.test(testset, verbose=False)
  File "/usr/local/lib/python2.7/dist-packages/surprise/prediction_algorithms/algo_base.py", line 152, in test
    for (uid, iid, r_ui_trans) in testset]
  File "/usr/local/lib/python2.7/dist-packages/surprise/prediction_algorithms/algo_base.py", line 99, in predict
    est = self.estimate(iuid, iiid)
  File "surprise/prediction_algorithms/matrix_factorization.pyx", line 243, in surprise.prediction_algorithms.matrix_factorization.SVD.estimate (surprise/prediction_algorithms/matrix_factorization.c:4637)
TypeError: unsupported operand type(s) for +: 'Decimal' and 'float'
Makefile:60: recipe for target 'importer-user-prod' failed
make: *** [importer-user-prod] Error 1
```

**Comment by prsolucoes** [comment]
I see the code of parse_line function and it has:

```python
return uid, iid, float(r) + self.offset, timestamp
```

So im presuming that rating always need be converted to float on custom dataset. Is it ok? Only float?

**Comment by NicolasHug** [comment]
Please give me the fisrt 10 lines of your dataset + your code.

**Comment by prsolucoes** [comment]
The problem was solve with force float convertion, the script dont break more.

But im using your sample for panda dataframe, im using in this way:

```python
for (user_id, product_id, rating, timestamp) in fnc.db_cursor:
    ratings_dict['itemID'].append(product_id)
    ratings_dict['userID'].append(user_id)
    ratings_dict['rating'].append(rating)

df = pd.DataFrame(ratings_dict)
data = Dataset.load_from_df(df[['userID', 'itemID', 'rating']], reader)
```

I changed:
> ratings_dict['rating'].append(rating)

To:
> ratings_dict['rating'].append(float(rating))

Becuase rating from mysql connector is comming as Decimal.

**Comment by NicolasHug** [comment]
Great.
